export const mockAgents = [
  {
    id: 1,
    name: 'FinChat AI',
    icon: require('@/assets/images/genesis/agent/agent_1.png'),
    score: 9.9,
    popularity: 1200,
    recommended: true,
    tags: ['AI Assistant', 'Intelligent reply'],
  },
  {
    id: 2,
    name: 'LegalBot',
    icon: require('@/assets/images/genesis/agent/agent_2.png'),
    score: 9.5,
    popularity: 980,
    recommended: true,
    tags: ['Legal Help', 'Smart Draft'],
  },
  {
    id: 3,
    name: 'MedicalGPT',
    icon: require('@/assets/images/genesis/agent/agent_3.png'),
    score: 9.7,
    popularity: 1500,
    recommended: false,
    tags: ['Diagnosis', 'Treatment Advice'],
  },
  {
    id: 4,
    name: 'EduTutor',
    icon: require('@/assets/images/genesis/agent/agent_4.png'),
    score: 9.2,
    popularity: 800,
    recommended: true,
    tags: ['Study Help', 'Exam Prep'],
  },
  {
    id: 5,
    name: 'TravelMate',
    icon: require('@/assets/images/genesis/agent/agent_5.png'),
    score: 8.9,
    popularity: 600,
    recommended: false,
    tags: ['Travel Advice', 'Planner'],
  },
  {
    id: 6,
    name: 'CodeHelper',
    icon: require('@/assets/images/genesis/agent/agent_6.png'),
    score: 9.4,
    popularity: 1100,
    recommended: true,
    tags: ['Debugging', 'Code Review'],
  },
  {
    id: 7,
    name: 'ChefBot',
    icon: require('@/assets/images/genesis/agent/agent_1.png'),
    score: 8.7,
    popularity: 450,
    recommended: false,
    tags: ['Recipes', 'Nutrition Tips'],
  },
  {
    id: 8,
    name: 'WellnessAI',
    icon: require('@/assets/images/genesis/agent/agent_3.png'),
    score: 9.1,
    popularity: 900,
    recommended: true,
    tags: ['Mental Health', 'Mindfulness'],
  },
];
export const mockIncome = [
  {
    user: 'admin',
    action: 'purchases one month service',
    datetime: '2025.5.01 12:00',
    amount: '+1.00usdt',
  },
  {
    user: 'admin',
    action: 'purchases one month service',
    datetime: '2025.5.01 12:00',
    amount: '+1.00usdt',
  },
  {
    user: 'admin',
    action: 'purchases one month service',
    datetime: '2025.5.01 12:00',
    amount: '+1.00usdt',
  },
];
export const orderMock = [
  {
    orderNo: '1324234365476',
    state: 'complete',
    price: '2.5 USDC / month',
    duration: '1 month',
    orderTime: '2025.5.1 12:00',
    paymentMethod: 'coinbase/usdc',
    totalPrice: '9.9',
    currency: 'USDC',
  },
  {
    orderNo: '1324234365477',
    state: 'pending',
    price: '3.0 USDC / month',
    duration: '1 month',
    orderTime: '2025.5.2 10:30',
    paymentMethod: 'metamask/usdc',
    totalPrice: '12.0',
    currency: 'USDC',
  },
  {
    orderNo: '1324234365478',
    state: 'complete',
    price: '1.5 USDC / month',
    duration: '3 months',
    orderTime: '2025.5.3 15:45',
    paymentMethod: 'binance/usdc',
    totalPrice: '4.5',
    currency: 'USDC',
  },
];
